# Generated by Django 4.1.3 on 2022-11-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atirgul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=31)),
                ('rangi', models.CharField(max_length=31)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
