# Generated by Django 4.1.3 on 2022-11-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_davlat_meva_moshina_odam_qoshiq_rasm_telefon_uy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moshinaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turr', models.CharField(max_length=31)),
                ('rangg', models.CharField(max_length=31)),
                ('yil', models.IntegerField(default=2004)),
                ('narx', models.IntegerField(default=70)),
                ('rasm', models.CharField(max_length=31)),
            ],
        ),
    ]
