# Generated by Django 4.1.3 on 2022-11-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_moshinaa_rasm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moshinaa',
            name='rasm',
            field=models.CharField(max_length=256),
        ),
    ]
